#!/bin/bash
# Set window to floating mode, then snap it to top right corner

resolution=($(getRes))
monitor_width=${resolution[0]}
monitor_height=${resolution[1]}

isFocusedWindowFloating() {
  bspc query -N -n focused.floating > /dev/null
  if [ $? -eq 0 ]; then
    echo true
  else
    echo false
  fi
}

case "$1" in
  up)
    if ($(isFocusedWindowFloating)); then
      bspc node -v 0 -20
    else
      bspc node -s north
    fi
    ;;
  down)
    if ($(isFocusedWindowFloating)); then
      bspc node -v 0 20
    else
      bspc node -s south
    fi
    ;;
  left)
    if ($(isFocusedWindowFloating)); then
      bspc node -v -20 0
    else
      bspc node -s west
    fi
    ;;
  right)
    if ($(isFocusedWindowFloating)); then
      bspc node -v 20 0
    else
      bspc node -s east
    fi
    ;;

  # These should only be used by floating windows
  top-left)
    if ($(isFocusedWindowFloating)); then
      window_xpos=$(returnWindowInfo.sh x)
      window_ypos=$(returnWindowInfo.sh y)
      bspc node -v "-$window_xpos" "-$window_ypos"
    fi
    ;;
  top-right)
    if ($(isFocusedWindowFloating)); then
      window_width=$(returnWindowInfo.sh w)
      window_xpos=$(returnWindowInfo.sh x)
      window_ypos=$(returnWindowInfo.sh y)
      bspc node -v "$(( monitor_width - window_width - window_xpos ))" "-$window_ypos"
    fi
    ;;
  bottom-left)
    if ($(isFocusedWindowFloating)); then
      window_height=$(returnWindowInfo.sh h)
      window_xpos=$(returnWindowInfo.sh x)
      window_ypos=$(returnWindowInfo.sh y)
      bspc node -v "-$window_xpos" "$(( monitor_height - window_height - window_ypos ))"

    fi
    ;;
  bottom-right)
    if ($(isFocusedWindowFloating)); then
      window_width=$(returnWindowInfo.sh w)
      window_height=$(returnWindowInfo.sh h)
      window_xpos=$(returnWindowInfo.sh x)
      window_ypos=$(returnWindowInfo.sh y)
      bspc node -v "$(( monitor_width - window_width - window_xpos ))" "$(( monitor_height - window_height - window_ypos ))"

    fi
    ;;
  top-center)
    if ($(isFocusedWindowFloating)); then
      window_width=$(returnWindowInfo.sh w)
      window_xpos=$(returnWindowInfo.sh x)
      window_ypos=$(returnWindowInfo.sh y)
      offset_center_x="$(( monitor_width / 2 - window_width / 2 ))"
      diff_x="$(( offset_center_x - window_xpos ))"
      bspc node -v "$diff_x" "-$window_ypos"
    fi
    ;;
  bottom-center)
    if ($(isFocusedWindowFloating)); then
      window_width=$(returnWindowInfo.sh w)
      window_height=$(returnWindowInfo.sh h)
      window_xpos=$(returnWindowInfo.sh x)
      window_ypos=$(returnWindowInfo.sh y)
      offset_center_x="$(( monitor_width / 2 - window_width / 2 ))"
      diff_x="$(( offset_center_x - window_xpos ))"
      bspc node -v "$diff_x" "$(( monitor_height - window_height - window_ypos ))"
    fi
    ;;
  center-left)
    if ($(isFocusedWindowFloating)); then
      window_height=$(returnWindowInfo.sh h)
      window_xpos=$(returnWindowInfo.sh x)
      window_ypos=$(returnWindowInfo.sh y)
      offset_center_y="$(( monitor_height / 2 - window_height / 2 ))"
      diff_y="$(( offset_center_y - window_ypos ))"
      bspc node -v "-$window_xpos" "$diff_y"
    fi
    ;;
  center)
    if ($(isFocusedWindowFloating)); then
      window_width=$(returnWindowInfo.sh w)
      window_height=$(returnWindowInfo.sh h)
      window_xpos=$(returnWindowInfo.sh x)
      window_ypos=$(returnWindowInfo.sh y)
      offset_center_x="$(( monitor_width / 2 - window_width / 2 ))"
      diff_x="$(( offset_center_x - window_xpos ))"
      offset_center_y="$(( monitor_height / 2 - window_height / 2 ))"
      diff_y="$(( offset_center_y - window_ypos ))"
      bspc node -v "$diff_x" "$diff_y"
    fi
    ;;
  center-right)
    if ($(isFocusedWindowFloating)); then
      window_width=$(returnWindowInfo.sh w)
      window_height=$(returnWindowInfo.sh h)
      window_xpos=$(returnWindowInfo.sh x)
      window_ypos=$(returnWindowInfo.sh y)
      offset_center_y="$(( monitor_height / 2 - window_height / 2 ))"
      diff_y="$(( offset_center_y - window_ypos ))"
      bspc node -v "$(( monitor_width - window_width - window_xpos ))" "$diff_y"
    fi
    ;;
esac
