#!/usr/bin/env bash

# Check for tiling status
bspc query -N -n focused.tiled > /dev/null

if [ $? -eq 0 ]; then
  window_state="tiled"
else
  window_state="floating"
fi

# Check for sticky status
bspc query -N -n focused.sticky > /dev/null

if [ $? -eq 0 ]; then
  sticky_state="sticky"
else
  sticky_state="not-sticky"
fi

if [ "$window_state" = "tiled" ] || [ "$sticky_state" = "sticky" ]; then
  bspc node -t floating -g sticky=on -l above
  
  resolution="$(xrandr --nograb --current | awk '/\*/ {printf $1; exit}')"
  monitor_width="${resolution/x*}"
  monitor_height="${resolution#*x}"
  wanted_width="$((monitor_width / 5))"
  wanted_height="$((monitor_height / 5))"
  cur_width="$(returnWindowInfo.sh w)"
  cur_height="$(returnWindowInfo.sh h)"
  diff_width="$(( cur_width - wanted_width ))"
  diff_height="$(( cur_height - wanted_height ))"

  bspc node -z bottom_right "-$diff_width" "-$diff_height"
  
  ~/.bin/bspc-smartmove bottom-right
else
  bspc node -t ~floating -g sticky=off -l normal
fi
