#!/usr/bin/env bash

pulse=$(which pulseaudio-ctl)
indicator="~/.config/lemonbar/vol.sh"
sound="$HOME/.data/sounds/blop.mp3"

muteStat=$(/usr/bin/pulseaudio-ctl full-status | cut -d " " -f2)

while getopts "mu:d:" flag; do
  case "${flag}" in
    m)
      $pulse mute
      sh -c $indicator &
      ;;
    u)
      if [ "$muteStat" = "yes" ]
      then
        $pulse mute
      fi
      $pulse up $OPTARG
      ffplay -nodisp -vn -autoexit "$sound"
      sh -c $indicator &
      ;;
    d)
      if [ "$muteStat" = "yes" ]
      then
        $pulse mute
      fi
      echo $OPTARG
      $pulse down $OPTARG
      ffplay -nodisp -vn -autoexit "$sound"
      sh -c $indicator &
  esac
done
