#!/usr/bin/env bash

pulse=$(which pulseaudio-ctl)
sound="$HOME/.data/sounds/blop.mp3"

muteStat=$(/usr/bin/pulseaudio-ctl full-status | cut -d " " -f2)

while getopts "mu:d:g" flag; do
  case "${flag}" in
    d)
      if [ "$muteStat" = "yes" ]
      then
        $pulse mute
      fi
      $pulse down $OPTARG
      ffplay -nodisp -vn -autoexit "$sound" &
      ;;
    g)
      $pulse full-status | cut -d" " -f1 -z
      ;;
    m)
      $pulse mute
      ;;
    u)
      if [ "$muteStat" = "yes" ]
      then
        $pulse mute
      fi
      $pulse up $OPTARG
      ffplay -nodisp -vn -autoexit "$sound" &
      ;;
  esac
done
