#!/usr/bin/env dash

if [ "$1" = "" ]
then
  echo "ERROR: Please provide file name (e.g. \`new-assignment a1\`)"
  exit 1
fi

NEWFILE=$1.tex

if [ ! -d "$pwd" ]
then
  mkdir $(pwd)/$1
fi
cp $HOME/Documents/TeX_Notes/setup-nvim/tex_assignment.sh $(pwd)/$1/$NEWFILE
nvim $(pwd)/$1/$NEWFILE
