#!/usr/bin/env bash

wpgc=$(which wpg)
editor=$(which nvim-qt)
fm=$(which thunar)

if [ -z $wpgc ]; then
  echo "wpg not found in path. Make sure that wpgtk is installed wpg is in your path."
  exit 1
fi

wpgcfgpath="$HOME/.config/wpg"
wpgprompt="  wpgtk"
template="Alt+t"
schemes="Alt+s"
config="Alt+c"
delete="Alt+d"
openinfm="Alt+t"
highlightcolor="Aqua"

. "$HOME/.config/rofi/script-configs/rofiwpg.conf"

copentag="<span color='${highlightcolor}'>"
cclosetag="</span>"
helpmsg="Actions:
${copentag}(Alt+t)${cclosetag} edit templates | ${copentag}(Alt+s)${cclosetag} edit schemes
${copentag}(Alt+c)${cclosetag} edit config | ${copentag}(Alt+d)${cclosetag} delete theme"

_rofi() {
  rofi -dmenu -markup-rows -i -p "${wpgprompt}" "$@"
}

edittemplate() {
  choice=$(${wpgc} -lt | _rofi -kb-custom-1 "${openinfm}" -mesg "${copentag}${openinfm}${cclosetag} open templates in file manager")
  val=$?

  case "$val" in
    0)
      if [ -n "$choice" ]; then
        ${editor} ${wpgcfgpath}/templates/${choice}
      fi
      ;;
    10)
      ${fm} ${wpgcfgpath}/templates/
      ;;
  esac
}

editschemes() {
  choice=$(ls ${wpgcfgpath}/schemes | _rofi)

  if [ -n "$choice" ]; then
    ${editor} ${wpgcfgpath}/schemes/${choice}
  fi
}

themechanger() {
  choice=$(${wpgc} -l | _rofi -mesg "${helpmsg}" -kb-custom-1 "${template}" -kb-custom-2 "${schemes}" -kb-custom-3 "${config}" -kb-custom-4 "${delete}")
  val=$?
  
  if [ $val -eq 0 ]; then
    echo ${choice}
  else
    echo $val
  fi
}

deletetheme() {
  choice=$(${wpgc} -l | _rofi -mesg "Which theme to delete?")
  confirm=$(echo "No|Yes" | _rofi -sep '|' -mesg "Really delete ${choice}?")
  if [ "$confirm" = "Yes" ]; then
    ${wpgc} -d ${choice}
    rofi -e "${choice} theme deleted"
  fi
}

main() {
  ret=$(themechanger)
  if [ "$ret" = "10" ]; then
    edittemplate
  elif [ "$ret" = "11" ]; then
    editschemes
  elif [ "$ret" = "12" ]; then
    ${editor} ${wpgcfgpath}/wpg.conf
  elif [ "$ret" = "13" ]; then
    deletetheme
  else
    ${wpgc} -s ${ret}
  fi
}

main
