#!/usr/bin/env dash

# Source: https://github.com/wstam88/rofi-fontawesome

arg=$1

options='-columns 3 -width 80 -lines 20 -bw 2 -yoffset -2'

if [ "$arg" = "update" ]
then
  curl -s https://raw.githubusercontent.com/wstam88/rofi-fontawesome/master/fa5-icon-list.txt > $HOME/.cache/fa5-icon-list.txt
  curl -s https://raw.githubusercontent.com/wstam88/rofi-fontawesome/master/icon-list.txt > $HOME/.cache/icon-list.txt
elif [ "$arg" = "fa5" ]
then
  selected=$(\
    cat $HOME/.cache/fa5-icon-list.txt \
      | rofi -dmenu -i -markup-rows \
      ${options} \
      -p "FontAwesome 5")
else
  selected=$(\
    cat $HOME/.cache/icon-list.txt \
      | rofi -dmenu -i -markup-rows \
      ${options} \
      -p "FontAwesome")
fi
  # exit if nothing is selected
  [[ -z $selected ]] && exit
  
  echo $(echo -n "$selected" |\
    awk -F';' -v RS='>' '
      NR==2{sub("&#x","",$1);print "\\u" $1;exit}'
  ) |  xclip -selection clipboard
