#!/usr/bin/env bash
# Written by Japorized <johnson5756 (at) live (dot) com>
# Required Dependencies:
# rofi, bc
# Optional Dependencies:
# mpv, thunar
#
# Make sure that your video files are renamed in the following format:
#   *- [x].ext
# where x is the episode number, which can be of any length.
# The only caveat with the naming of files is that the episode number
# must be enclosed in square brackets, and place at the very end of the
# filename right before the extension.

# configs
rofiprompt="ア rofianime"
animedir="$HOME/Videos/Anime"
vidplayer="/usr/bin/mpv"
filemanager="/usr/bin/thunar"
fileext="(.mkv|.mp4|.webm)" # use regex (PCRE)
renamers="HorribleSubs|Teasing Anon" # |-separated
rofiopts=""
dmenuopts=""

if [ ! -e $vidplayer ]; then
  rofi -e "$vidplayer does not exist. Please manually configure rofianime".
  exit 1
fi

# keybindings
goback="Alt+c"
useRenamer="Alt+r"
openInFM="Alt+t"

# color(s)
highlightcolor='Aqua'

# load configs
. "$HOME/.config/rofi/script-configs/rofianime.conf"

_rofi() {
  rofi ${rofiopts} -sep '|' -dmenu -i -p "${rofiprompt}" ${dmenuopts} "$@"
}

_renamer() {
  case "$1" in
    "HorribleSubs" | "Teasing Anon")
      for f in *"$1"* ; do
        filename=$(echo $f \
          | sed "s/\[$1\] //g" \
          | sed 's/ \[[0-9]*p\]//g' \
          | sed -E "s/ - ([0-9]+\.?[0-9]+)/ - [\1]/g")
        mv "$f" "$filename"
      done && rofi -e "Success"
      ;;
  esac
}

getAnime() {
  IFS=$'\n'
  animearr=($(ls | sed 's/:.*//'))
  unset IFS
  
  animelist=""
  for idx in "${!animearr[@]}"
  do
    if [ -z "$animelist" ]; then
      animelist="${animearr[$idx]}"
    else
      animelist="$animelist|${animearr[$idx]}"
    fi
  done
  
  anime=$(echo $animelist | _rofi)
  echo "$anime"
}

getEpisode() {
  IFS=$'\n'
  # we shall grab only the files with the provided extensions
  episodearr=($(ls | grep -E $fileext | sed 's/:.*//'))
  unset IFS
  
  lastWatchedEp=$(getBookmark .bookmark)
  if [ -n $lastWatchedEp ]; then
    nextEp=$(echo $lastWatchedEp + 1 | bc)
  else
    nextEp=""
  fi
  
  episodelist=""
  for idx in "${!episodearr[@]}"
  do
    if [ -z "$episodelist" ]; then
      episodelist="${episodearr[$idx]}"
    else
      if [ -n $nextEp ]; then
        # try to put next episode as the first choice
        curEp=$(echo $(getEpNum "${episodearr[$idx]}") | bc)
        if [ $curEp != $nextEp ]; then
          episodelist="$episodelist|${episodearr[$idx]}"
        else
          episodelist="${episodearr[$idx]}|$episodelist"
        fi
      else
        episodelist="$episodelist|${episodearr[$idx]}"
      fi
    fi
  done

  rofimsg="<i><b>Last Episode:</b> $lastWatchedEp</i>
<span color='${highlightcolor}'>${goback}</span> to go back | <span color='${highlightcolor}'>${useRenamer}</span> to automagically rename certain files | <span color='${highlightcolor}'>${openInFM}</span> open in file manager"

  episode=$(echo $episodelist \
    | _rofi -mesg "$rofimsg" ${dmenuopts} \
      -kb-custom-1 "${goback}" -kb-custom-2 "${useRenamer}" \
      -kb-custom-3 "${openInFM}" )

  val=$?
  case "$val" in
    10) main ;;
    11) renameFiles ;;
    12) ${filemanager} . ;;
    1) exit 0 ;;
    *) echo "$episode"
  esac
}

renameFiles() {
  renameChoice=$(echo "$renamers" | _rofi -mesg "Pick an option")
  _renamer "$renameChoice"
}

getEpNum() {
  epnum=$(echo "$1" | sed -E "s/.+ - \[(.+)\]$fileext/\1/g")
  echo $epnum
}

setBookmark() {
  echo $(getEpNum "$1") > .bookmark
}

getBookmark() {
  if [ -e .bookmark ]; then
    cat .bookmark
  else
    echo "" > .bookmark
  fi
}

main() {
  cd "$animedir"

  animeRes=$(getAnime)
  if [ -z "$animeRes" ]; then
    exit 0
  fi

  cd "$animeRes"

  epiRes=$(getEpisode)
  if [ -z "$epiRes" ]; then
    exit 0
  fi
  setBookmark "$epiRes"
  ${vidplayer} "${epiRes}"
}

main
