#!/usr/bin/env bash

_rofi() {
  rofi -sep '|' -columns 5 -lines 1 -disable-history true -cycle true \
    -theme ~/.config/rofi/theme/rofi-smallmenu.rasi -location 5 -width 280 -height 20 \
    -dmenu -font "Hack Nerd Font 10" -mesg "what to do"
}

choice=$(echo -n "|||||" | _rofi)

case "$choice" in
  )
    /usr/bin/gimp "$1/$2"
    ;;
  )
    /usr/bin/feh "$1/$2"
    ;;
  )
    /usr/bin/thunar "$1"
    ;;
  )
    rm "$1/$2"
    ;;
  )
    dest=$(/usr/bin/zenity --file-selection --save --confirm-overwrite)

    filename=${dest##*/}
    destExt=${filename##*.}
    if [ "$destExt" != "png" ]; then
      convert "$1/$2" "$dest"
      rm "$1/$2"
    else
      mv "$1/$2" "$dest"
    fi

    ;; 
  )
    /usr/bin/dragon-drag-and-drop "$1/$2"
    ;;
esac
