#!/usr/bin/env bash

mpc_status() {
  status=$(mpc | sed -n 2p | awk -F " " '{print $1}')
  echo ${status} | sed "s/\&/\&amp;/g"
}

_rofi() {
  rofi -sep '|' -columns 8 -lines 1 -disable-history true -cycle true \
    -theme ~/.config/rofi/theme/rofi-smallmenu.rasi -location 5 -width 550 -height 20 \
    -dmenu -font "Hack Nerd Font 10" -mesg "$(mpc_status) $(mpc current | sed 's/\&/\&amp;/g')"
}

inform() {
  sleep 0.5
  show-lemonbar nowplaying
}

choice=$(echo -n "||||凌||綾|||" | _rofi)

case "$choice" in
  )
    mpc cdprev && inform
    ;;
  )
    mpc toggle && inform
    ;;
  )
    mpc next && inform
    ;;
  )
    vol=$(echo -n "100|75|50|25|+5|-5" | _rofi)
    mpc volume ${vol}
    ;;
  )
    mpc repeat && inform
    ;;
  凌)
    mpc random && inform
    ;;
  綾)
    mpc single && inform
    ;;
  )
    cross=$(echo -n "0|1|5|7|10|15" | _rofi)
    mpc crossfade ${cross}
    ;;
  )
    mpc consume && inform
    ;;
  )
    systemctl --user restart mpd.service
    ;;
esac
