#!/usr/bin/env bash

wpgc=$(which wpg)
editor=$(which nvim-qt)
fm=$(which thunar)

if [ -z $wpgc ]; then
  echo "wpg not found in path. Make sure that wpgtk is installed wpg is in your path."
  exit 1
fi

wpgcfgpath="$HOME/.config/wpg"
wpgprompt=" wpgtk"
template="Alt+t"
schemes="Alt+s"
config="Alt+c"
delete="Alt+d"
openinfm="Alt+t"
highlightcolor="Aqua"

# Configuration
. "$HOME/.config/rofi/script-configs/rofiwpg.conf"

printKey() {
  echo -n "<b><span color='${highlightcolor}'>($1)</span></b>"
}

_rofi() {
  rofi -dmenu -markup-rows -i -p "${wpgprompt}" "$@"
}

helpmsg="Actions:
$(printKey ${template}) edit templates | $(printKey ${schemes}) edit schemes
$(printKey ${config}) edit config    | $(printKey ${delete}) delete theme"

edittemplate() {
  choice=$(${wpgc} -lt | _rofi -kb-custom-1 "${openinfm}" \
    -mesg "$(printKey ${openinfm}) open templates in file manager")
  retval=$?

  case "$retval" in
    10)
      ${fm} ${wpgcfgpath}/templates/
      ;;
    1) exit 0 ;;
    0)
      ${editor} ${wpgcfgpath}/templates/${choice}
      ;;
  esac
}

editschemes() {
  choice=$(ls ${wpgcfgpath}/schemes | _rofi)
  retval=$?

  case "$retval" in
    1) exit 0 ;;
    0)
      ${editor} ${wpgcfgpath}/schemes/${choice}
      ;;
  esac
}

deletetheme() {
  choice=$(${wpgc} -l | _rofi -mesg "Which theme to delete?")
  retval=$?
  
  case "$retval" in
    1) exit 0 ;;
    0)
      confirm=$(echo "No|Yes" | _rofi -sep '|' -mesg "Really delete ${choice}?")
      retval=$?
      case "$retval" in
        1) exit 0 ;;
        0)
          if [ "$confirm" = "Yes" ]; then
            ${wpgc} -d ${choice}
            rofi -e "${choice} theme deleted"
          fi
          ;;
      esac
  esac
}

main() {
  choice=$(${wpgc} -l | _rofi -mesg "${helpmsg}" \
    -kb-custom-1 "${template}" -kb-custom-2 "${schemes}" \
    -kb-custom-3 "${config}" -kb-custom-4 "${delete}")
  retval=$?

  case "$retval" in
    10) edittemplate ;;
    11) editschemes ;;
    12) ${editor} ${wpgcfgpath}/wpg.conf ;;
    13) deletetheme ;;
    1) exit 0 ;;
    0) ${wpgc} -s ${choice}
  esac
}

main
