#!/usr/bin/env dash

prp="\e[35m"
rst="\e[0m"

img=$1
backend=$2
light=$3

if test -z "${img}"
then
  echo "Error: No argument provided. Please provide image file path."
  exit 1
fi

if [ "$img" = "-h" ] || [ "$img" = "--help" ]
then
  echo "Usage: wal-it <img_path> <backend> <light=light>
  
backend choices: wal, colorz

Pass 'light' as the 3rd argument for light background. Leave empty for default dark.
All arguments are mandatory."
  exit 0
fi

# Setting up frequently used wallpapers
case $img in
  "pinetrees")
    img=$HOME/Pictures/Wallpapers/pinetrees.png
    ;;
  "hydrangea")
    img=$HOME/Pictures/Wallpapers/konohanakitan_hydrangea.jpg
    ;;
  "oldbridge")
    img=$HOME/Pictures/Wallpapers/old-bridge-intothedistance.jpg
    ;;
esac

/usr/bin/notify-send "Running: wal-it"

echo "${prp}Running: wal${rst}"
echo $light
if [ "$light" = "light" ]
then
  $HOME/.local/bin/wal -l -i "${img}" -g --backend $backend
elif [ "$light" != "" ] || [ "$light" = "dark" ]
then
  $HOME/.local/bin/wal -i "${img}" -g --backend $backend
else
  echo "pass 'light' for setting to light mode"
fi

echo "\n${prp}Running: wal-vis${rst}"
$HOME/.bin/wal-vis

echo -n "\n${prp}Refreshing bspwm colors${rst}"
sh -c "$HOME/.config/bspwm/bspwm-colors.sh &"
echo ": Done"

echo -n "${prp}Refreshing lemonbar${rst}"
sh -c "$HOME/.bin/refresh-indicators.sh"
echo ": Done"

# if [ "$lock" = "lock" ]
# then
#   echo "\nRunning: betterlockscreen -u"
#   /usr/bin/betterlockscreen -u "${img}"
# fi

sleep 0.5
/usr/bin/notify-send "Completed: wal-it"
