#!/usr/bin/env dash

prp="\e[35m"
rst="\e[0m"

img=$1
backend=$2

if test -z "${img}"
then
  echo "Error: No argument provided. Please provide image file path."
  exit 1
fi

# Setting up frequently used wallpapers
case $img in
  "pinetrees")
    img=$HOME/Pictures/Wallpapers/pinetrees.png
    ;;
  "hydrangea")
    img=$HOME/Pictures/Wallpapers/konohanakitan_hydrangea.jpg
    ;;
  "oldbridge")
    img=$HOME/Pictures/Wallpapers/old-bridge-intothedistance.jpg
    ;;
esac

/usr/bin/notify-send "Running: wal-it"

echo "${prp}Running: wal${rst}"
$HOME/.local/bin/wal -i "${img}" -g --backend $backend

echo "\n${prp}Running: wal-steam${rst}"
$HOME/.local/bin/wal-steam -w

echo "\n${prp}Running: wal-vis${rst}"
$HOME/.bin/wal-vis

echo -n "\n${prp}Refreshing bspwm colors${rst}"
sh -c "$HOME/.config/bspwm/bspwm-colors.sh &"
echo ": Done"

echo -n "${prp}Refreshing lemonbar${rst}"
sh -c "$HOME/.bin/refresh-indicators.sh"
echo ": Done"

# if [ "$lock" = "lock" ]
# then
#   echo "\nRunning: betterlockscreen -u"
#   /usr/bin/betterlockscreen -u "${img}"
# fi

sleep 0.5
/usr/bin/notify-send "Completed: wal-it"
